language: generic
sudo: required

services:
  - docker

env:
  - OPENCV_VERSION=3.4.0
  - OPENCV_VERSION=3.4.1

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - docker-ce

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t opencv-java -f $OPENCV_VERSION/Dockerfile.armhf .
  - docker images
  - docker tag opencv-java $DOCKER_USERNAME/opencv-java:$OPENCV_VERSION-arm-test
  - docker push $DOCKER_USERNAME/opencv-java:$OPENCV_VERSION-arm-test
